pipeline {
    agent any
    tools {
        maven '3.9.5'
        nodejs 'nodejs-18'
    }
    environment {
        NEXUS_CREDENTIAL_ID = "nexus"
        NEXUS_URL = 'http://localhost:6666'
        NEXUS_REPO = 'dockerhosted-repo'
        DOCKER_IMAGE_NAME = "car-pooling-fe:${BUILD_ID}"
    }

    stages {
        stage("checkout code"){
            steps {
                script {
                    git branch: 'main', url: 'https://github.com/hjaijhoussem/Car-pooling-frontend.git',  credentialsId: 'github-jenkins'
                }
            }
        }

        stage('Quality Analysis'){
            steps{
                withSonarQubeEnv('mysonar'){
                   sh """
                    npx sonar-scanner \
                        -Dsonar.projectKey=car-pooling-fe \
                        -Dsonar.projectName=car-pooling-fe \
                        -Dsonar.sources=. \
                    """
                }
            }
        }

        stage('Quality Gate'){
            steps{
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE_NAME} ."
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker tag ${DOCKER_IMAGE_NAME} localhost:6666/repository/dockerhosted-repo/${NEXUS_REPO}/${DOCKER_IMAGE_NAME}"
                    sh "docker push localhost:6666/repository/dockerhosted-repo/${NEXUS_REPO}/${DOCKER_IMAGE_NAME}"
                }
            }
        }
    }
}
