---
- name: Deploy Docker Containers
  hosts: local
  become: yes
  vars:
    image_name: "{{ image_name }}"  # This variable will be overridden in the Jenkins pipeline

  tasks:
    - name: Check if the Docker network exists
      docker_network:
        name: "{{ network_name }}"
        state: present
        
    - name: Stop and remove the existing container if it exists
      docker_container:
        name: car-pooling-fe
        state: absent
      ignore_errors: yes  # Prevents failure if the container does not exist

    - name: Pull the Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Start Docker container
      docker_container:
        name: car-pooling-fe
        image: "{{ image_name }}"
        state: started
        networks:
          - name: "{{ network_name }}"
        published_ports:
          - "3000:80"
